# Generated by Django 3.2.9 on 2022-06-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0003_alter_basket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasketManager',
        ),
    ]
